### ISSUE TITLE
Load Github token from git config

### ISSUE THREAD

**Issue by Tom32i** [Elao/github-agile-dashboard#6]
It seems better to avoid loading the Github Token from an environment variable.
Something like [this](https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens) seems preferable: 

`composer config -g github-oauth.github.com <oauthtoken>`

Thanks @chalasr for the suggestion.

**Comment by ogizanagi** [comment]
Actually, it seems Github rather recommend using `git config --global github.token`. For ref, the page I showed you lately: https://github.com/blog/180-local-github-config ^^
